# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "minitest", "~> 5.14", :group => :development

gem "aws-sdk-s3", "~> 1.79"

gem "timecop", "~> 0.9.1", :group => :development
