service: jira-datastudio
provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: ruby2.7
  memorySize: 192
  logRetentionInDays: 14
  timeout: 28
  httpApi:
    payload: '2.0'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: CacheBucket
    - Effect: 'Allow'
      Action:
       - s3:*Object
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: CacheBucket
            - '/*'
  environment:
    GEM_PATH: /opt/ruby/2.5.0
    STAGE: ${self:custom.stage}
    CACHE_BUCKET_NAME: ${self:custom.cacheBucketName}
custom:
  stage: ${opt:stage, env:SLS_STAGE, 'dev'}
  cacheBucketName: jira-datastudio-${self:custom.stage}
functions:
  report:
    handler: entry_report.run
    package:
      exclude:
        - ./spec
        - ./Gemfile
        - ./Gemfile.lock
        - ./run_all_specs.rb
        - ./run_locally.rb
      # include:
      #   - entry_report.rb
      #   - lib/**/*.rb
    # layers:
    #   - { Ref: GemsLambdaLayer }
    events:
      - httpApi:
          method: POST
          path: /jira-kanban
resources:
  Resources:
    CacheBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.cacheBucketName}
        LifecycleConfiguration:
          Rules:
            -
              ExpirationInDays: 1
              Prefix: '/'
              Status: Enabled 
# layers:
#   gems:
#     name: ${self:provider.stage}-gems
#     description: Contains ruby gems
#     compatibleRuntimes:
#       - ruby2.7
#     retain: false
#     package:
#       artifact: gem_layer.zip
