name: CI
on: push
jobs:
  run_ruby_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Install gems
      working-directory: ./serverless
      run: bundle install
    - name: Run tests
      working-directory: ./serverless
      run: ruby ./run_all_specs.rb