name: Deploy master branch
on:
  push:
    branches:
      - master
jobs:
  run_ruby_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Install gems
      working-directory: ./serverless
      run: bundle install
    - name: Run tests
      working-directory: ./serverless
      run: ruby ./run_all_specs.rb
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}